name: Flutter PR
on:
    pull_request:
     branches: 
        - main
     paths-ignore:
        - 'README.md'
        - server/**
        - proto/
        - .github/workflows/server_cicd.yml
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-java@v1
              with:
                  java-version: '12.x'
            - uses: subosito/flutter-action@v1
              with:
                  channel: 'stable'
            - uses: actions/checkout@v2
            - run: flutter pub get
              working-directory: client
            - run: sh ../scripts/flutter_analyze.sh
              working-directory: client
            - name: Restore keystore
              run: |
                mkdir -p android/keystore
                echo "${{ secrets.STORE_FILE }}" | base64 -d > android/keystore/my-release-key.jks
              working-directory: client
            - name: Build release APK
              run: flutter build apk --release
              working-directory: client
              env:
                STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
                KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
                STORE_FILE: android/keystore/my-release-key.jks
            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: release.apk
                  path: client/build/app/outputs/apk/release/app-release.apk
     


